### ISSUE TITLE
Crash on save

### ISSUE THREAD

**Issue by rayannott** [rayannott/number-shop#3]
The game crashes on save when the `saves` directory does not exist.
```
Traceback (most recent call last):
  File "D:\contents\pythoncode\number-hunter\main.py", line 10, in <module>
    main()
  File "D:\contents\pythoncode\number-hunter\main.py", line 6, in main
    app.menu()
  File "D:\contents\pythoncode\number-hunter\ui.py", line 67, in menu
    self.execute_command_menu(inp.split())
  File "D:\contents\pythoncode\number-hunter\ui.py", line 114, in execute_command_menu
    self.run()
  File "D:\contents\pythoncode\number-hunter\ui.py", line 307, in run
    self.execute_command(inp)
  File "D:\contents\pythoncode\number-hunter\ui.py", line 186, in execute_command
    self.save_game()
  File "D:\contents\pythoncode\number-hunter\ui.py", line 311, in save_game
    with open(os.path.join(SAVES_DIR, self.save_name), 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'saves\\ncJjbjmgiH.pi'
```

**Comment by rayannott** [comment]
Fixed
